### ISSUE TITLE
Use xebium as a fixture

### ISSUE THREAD

**Issue by ahmah11** [xebia/Xebium#142]
Hi,

I see that i have to run the xebium project which will run fitnesse .

Is there a way to use xebium as a jar file and give the path to this file from an independent fitnesse ?

**Comment by ahmah11** [comment]
Thanks, what command should i use to generate the xebium fixture jar file ?

**Comment by cwortel** [comment]
Hey,

It's possible to build a JAR file. This can be done by running Maven with "*mvn
-Pjar-with-dependencies package*" in the Xebium source directory.
This will produce a JAR file in your /target directory, which you can
execute using "*java -cp xebium-0.x.jar fitnesseMain.FitNesseMain*".
In this case you can start Xebium with the java-command, without using
maven. All you need is the target-directory.

Or use any other preffered way to add to your fitnesse classpath.

Regards,

Cirilo

**Comment by raboof** [comment]
@ahmah11 Did this answer your question?
