### ISSUE TITLE
Open an existing session in Xebium

### ISSUE THREAD

**Issue by saurabhsehgal1** [xebia/Xebium#143]
Hi, 
I want to open an existing session in Xebium. Let me give you an example:
1. I looged in to the application.
2. Navigate to Page1
3. Navigate to Page2
4. Navigate to Page3

Now in my new script I directly want to open Page 3. Is there anyway in Xebium to do that?
I tried using the following command but its not working. It does not recognize the URL.
| start browser | firefox | on url | http://www.abc.com/abcd/Page3|

However when I directly paste the URL in the address bar it opens up the Page3 directly.

Thanks!

**Comment by cwortel** [comment]
Hi,

If “http://www.abc.com <http://www.abc.com/>” is your base_url, any path behind it you can be opened, using the “open" command.

| script |
| start browser |firefox | on url | http://www.abc.com <http://www.abc.com/> |
| open | on | abcd/Page3 |

Regards,

Cirilo

**Comment by raboof** [comment]
@saurabhsehgal1 does this answer your question?
