### ISSUE TITLE
Running test/suite in parallel

### ISSUE THREAD

**Issue by aquddos123** [xebia/Xebium#152]
Is it possible to run multiple FitNesse test/suite in parallel under this project configuration?

We are using this project configuration in conjunction with SauceLabs to run several tests which are taking 6 to 7 hours to complete. We really want to leverage SauceLabs capability to run test in parallel but does not have a workaround on FitNesse side how to do it. Does anyone have any clue how we can do so using this project? 

I'm simply invoking an integrated build on parent suite using the following command:

```mvn clean -P fitnesse-integration integration-test```

with the following command line arguments:
```
-p 8001
-c Project.UserInterface?responder=suite&format=html
-d .  
```

**Comment by amolenaar** [comment]
Hi,

Unfortunately FitNesse does not support parallel execution (there is an issue for it though: https://github.com/unclebob/fitnesse/issues/806). 
What you can do is spawn multiple execution jobs, each one executing one of the sub suites.

If you have any idea on how you would like parallel execution in FitNesse to work, please comment on the FitNesse issue mentioned.

Regards,

Arjan

**Comment by raboof** [comment]
Closing because this is an upstream issue
