### ISSUE TITLE
xebium running from command line 

### ISSUE THREAD

**Issue by kiranjot** [xebia/Xebium#47]
Is it possible to run xebium test from command line 
i.e providing a particular test page.

**Comment by mcgurkar** [comment]
Hi, could you please guide me on how to run the xebium from command line, 
appreciate if you could send me the modified pom.xml to mcgurkar@gmail.com

**Comment by amolenaar** [comment]
You can have a look at the pom.xml of this very project: https://github.com/xebia/Xebium/blob/master/pom.xml#L297

**Comment by mcgurkar** [comment]
Hi i looked at this Pom.xml and the pom.xml that i have both are same, i did sent an email separately to you with the .xml. please provide instructions on how to run from command prompt..
